server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  ## 注册服务到eureka里去
spring:
  application:
    name: oasis-serv
  datasource:
    url: jdbc:mysql://cdb-nb7925gu.cd.tencentcdb.com:10072/testJson?useSSL=true&serverTimezone=UTC
    username: root
    password: 123qwe!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.106.227.22
    port: 6379

#mybatis-plus:
#  mapper-locations: classpath:dataImpl/*/*Mapper.xml
