server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: oasis-serv
  datasource:
    url: jdbc:mysql://cdb-nb7925gu.cd.tencentcdb.com:10072/acmieee?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456qwerty!@#$%^
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.106.227.22
    port: 6379

mybatis:
  mapper-locations: classpath:daoImpl/*DAO.xml
