server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: oasis-serv
  datasource:
    url: jdbc:mysql://cdb-nb7925gu.cd.tencentcdb.com:10072/acmieee?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456qwerty!@#$%^
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.106.227.22
    port: 6379
    password: docker@redis.com11037
  data:
    neo4j:
      uri: bolt://152.136.140.52:7687
      username: neo4j
      password: neo4j.com147258369

mybatis:
  mapper-locations: classpath:daoImpl/*DAO.xml
