pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
		stage('Jacoco') {
            steps {
		       jacoco()
			}
		}
		stage('Image') {
		    steps {
		        sh 'mvn docker:build -Ddocker.image.name=${JOB_NAME} -Ddocker.image.tag=1.0.0.${BUILD_ID}'
		    }
		}
		stage('PushImage') {
            steps {
       	        sh 'mvn docker:push -Ddocker.image.name=${JOB_NAME} -Ddocker.image.tag=1.0.0.${BUILD_ID}'
       	        sh 'mvn docker:removeImage -Ddocker.image.name=${JOB_NAME} -Ddocker.image.tag=1.0.0.${BUILD_ID}'
       	   }
       	}
        stage('Startup') {
            steps {
                withEnv(['JENKINS_NODE_COOKIE=dontkillme']){
			        sh 'docker service update --image registry.cn-hangzhou.aliyuncs.com/nju_oasis/${JOB_NAME}:1.0.0.${BUILD_ID} ${JOB_NAME}'
		        }
            }
        }
    }
}